version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  db_dev:
    image: postgres
    volumes:
      - ./tmp/db_dev:/var/lib/postgresql/data
  redis:
    image: redis
    command: "redis-server"
  production:
    build:
      context: .
      dockerfile: production.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ingresse_production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  development:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && dotenv bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ingresse_development
    ports:
      - "3001:3000"
    depends_on:
      - db_dev
      - redis
