default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  host: db_dev
  database: <%= "#{ENV['DB_NAME']}_development" %>


test:
  <<: *default
  host: db_dev
  database: <%= "#{ENV['DB_NAME']}_test" %>
